# Generated by Django 4.0.5 on 2022-06-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0005_business_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
