# Generated by Django 4.0.5 on 2022-06-19 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0006_alter_business_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='detail',
        ),
    ]
